feat(LINGUIST-201): Added profile and hobby related controller service and repository
LinguistAI/user pull request #20
Opened 2024-02-19 17:14 UTC by elif-krvan

2024-02-19 19:02 UTC, can-aslan requested changes
Looks very good, just left some minor comments 🚀

2024-02-20 12:19 UTC, elif-krvan commented on src/main/java/app/linguistai/bmvp/controller/ProfileController.java
> +    @PutMapping(consumes = MediaType.APPLICATION_JSON_VALUE, path = "")
napim

2024-02-20 12:19 UTC, can-aslan commented on src/main/java/app/linguistai/bmvp/controller/ProfileController.java
> +    @GetMapping("")
`"ne"` gibi soru ekleri ayrı yazılır 🤓

2024-02-20 12:19 UTC, elif-krvan commented on src/main/java/app/linguistai/bmvp/model/profile/Hobby.java
> +    private Integer id;
They are just hobbies there is no need to make it too complicated

2024-02-20 12:19 UTC, can-aslan commented on src/main/java/app/linguistai/bmvp/controller/ProfileController.java
> +    @PutMapping(consumes = MediaType.APPLICATION_JSON_VALUE, path = "")
duzelt

2024-02-21 21:31 UTC, can-aslan commented on src/main/java/app/linguistai/bmvp/model/profile/Hobby.java
> +    private Integer id;
Can we make it at least `Long`

2024-02-22 19:01 UTC, elif-krvan commented on src/main/java/app/linguistai/bmvp/model/profile/Hobby.java
> +    private Integer id;
no

2024-02-23 21:09 UTC, merged